- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentComCap ## Наша кепка ЦК ImperialClothes 
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCentCom ## Наш перчатки ЦК ImperialClothes
    outerClothing: ClothingOuterArmorCentCom ## Наш бронежилет ЦК ImperialClothes
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
